### ISSUE TITLE
Switch to SMD instead of THT for all BME related components

### ISSUE THREAD

**Issue by Schluggi** [Schluggi/AIOsense#12]
Both resistors and the capacitor are only for the BME chips. These chips can only soldered by using a heatgun or a heating plate. 
So everyone who hasn't access to this kind of equipment will use a BME module instead and does not need to solder these parts. 

So there is no need to make this parts consumer friendly (alias THT).

**Comment by Schluggi** [comment]
Update: Both resistors are needed in any case of I²C. So there are not related to the BME chips and we will revoke our changes.

**Comment by florianmulatz** [comment]
Hi Schluggi, not sure what is it about now. The Sensors are designed with SMD Footprints on your PCB. Would you redesign it for "Sensor-Modules" like this one? --> [BME680_DevBoard](https://www.reichelt.at/at/de/entwicklerboards-sensor-bosch-bme680-debo-sens-bme680-p253653.html?&trstct=pos_1&nbc=1) or this one [BME_280_DevBoard](https://www.reichelt.at/at/de/entwicklerboards-temperatur-feuchtigkeits-und-drucksensor--debo-bme280-p253982.html?&trstct=pos_1&nbc=1).

Anyhow of course the price is quite different on using a DevBoard instead of the sensor itself (aroun3 times more for the small-board).

I think the resistors and capacitors around the BME's will also be obsolete if using the dev-boards (I'm not able to find schematics for those but it looks like that they have a few components "onBoard")

Cheers Flo

**Comment by florianmulatz** [comment]
deleted my post since I've overseen that there is already a v2 Branch. Cheers

**Comment by Schluggi** [comment]
Please notice #65.
