### ISSUE TITLE
Newbie has some questions / ideas

### ISSUE THREAD

**Issue by lougreenwood** [Schluggi/AIOsense#85]
**Category**
- [x] Hardware / PCB
- [ ] Software / ESPHome

**Whats your idea?**
Hi, I'm a newbie to ESP32 & hardware in general (although I am a professional software dev, so I'm not completely naive).

I'm looking into building something like this, but I have a few unique requirements and I wondered if there was plans for anything similar with this project.

- Thread support, as far as I see, there is an ESP32 board with Thread incoming. I see that the FP2 went to wifi (I believe that the FP1 was Zigbee IIRC) and Aqara explained this as being because Zigbee didn't have the bandwidth for their sensor. I wondered if this device could realistically be run using Thread or would it have the same bandwidth limitations?
- I'm also considering hard wiring some sensors & using PoE. Can this sensor support the PoE ESP board (obviously the case won't fit this board version...)
- Are there any plans to build a waterproof version of the sensor? I would like to mount one in bathrooms, so having one with something similar to IPX4 would be useful for mounting in bathroom zone 2 or above. Has something like this been considered?

Thanks for creating this exciting project, I'm looking forward to hopefully using it as my springboard into building my own sensors & hardware to power my smart home! 🙇‍♂️

**Comment by Schluggi** [comment]
Hi @lougreenwood,

thank you for your input and sorry for the late response (too many projects...).

- As far as I can see there is no ESPHome support for the ESP32-C6 and ESP32-H2 yet. If this will change in the future I've no problem to support them as well. 
- PoE was already discussed [here](https://github.com/Schluggi/AIOsense/discussions/22#discussioncomment-5024127)
- I've one unit in my (very small) bathroom since 8 months and I can't see any sign of corrosion yet. So for bathroom applications its just fine I think. IPX4 is not that easy to achieve. If we just cover the whole unit in varnish (is this the right term in english?) the PCB would be very waterproof but a lot of the sensors would not work anymore.

To tease my future plans of this project: I want to include a speaker and a (working) mic. Not that easy in this size..
